name: ci
on:
  push:
    branches:
      - develop
jobs:
  spotlessJavaCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SetUp JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew 
        working-directory: ./backend


      - name: spotless check
        run: ./gradlew spotlessCheck
        working-directory: ./backend

      - name: test and analyze
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test sonar --info --stacktrace
        working-directory: ./backend
